services:
  auth-service:
    build:
      context: .
      dockerfile: backend/services/auth-service/Dockerfile
    container_name: edutech-auth-service
    restart: always
    ports:
      - '8001:8001'
    env_file:
      - backend/services/auth-service/.env

  course-service:
    build:
      context: ./backend/services/course-service
      dockerfile: Dockerfile
    container_name: edutech-course-service
    restart: always
    ports:
      - '8002:8002'
    environment:
      - PORT=8002
      # Đưa chính xác thông tin Supabase vào đây:
      - DB_HOST=aws-0-ap-southeast-1.pooler.supabase.com
      - DB_PORT=5432
      - DB_USER=postgres.ieqfabmuxoigwpiwvwmw
      - DB_PASSWORD=edutech@2026
      - DB_NAME=course_service

  web:
    build:
      context: .
      dockerfile: apps/web/Dockerfile
    container_name: edutech-web
    restart: always
    ports:
      - '5173:5173'
    environment:
      VITE_API_AUTH_URL: "http://localhost:8001/api/v1"
    depends_on:
      - auth-service

volumes:
  postgres_data: