services:
  auth-service:
    build:
      context: .
      dockerfile: backend/services/auth-service/Dockerfile
    container_name: edutech-auth-service
    restart: always
    ports:
      - '8001:8001'
    env_file:
      - backend/services/auth-service/.env

  course-service:
    build:
      context: ./backend/services/course-service
      dockerfile: Dockerfile
    container_name: edutech-course-service
    restart: always
    ports:
      - '8002:8002'
    environment:
      - PORT=8002
      # Giữ nguyên 100% Supabase cũ:
      - DB_HOST=aws-0-ap-southeast-1.pooler.supabase.com
      - DB_PORT=5432
      - DB_USER=postgres.ieqfabmuxoigwpiwvwmw
      - DB_PASSWORD=edutech@2026
      - DB_NAME=course_service

  quiz-service:
    build:
      context: ./backend/services/quiz-service
      dockerfile: Dockerfile
    container_name: edutech-quiz-service
    restart: always
    ports:
      - '8003:8003'
    environment:
      - PORT=8003
      # MongoDB Atlas độc lập
      - MONGO_URI=mongodb+srv://thugoodcat_db_user:BVpl3MX7cQ05zEqS@edutech.u4syj9y.mongodb.net/edutech_quiz_db?retryWrites=true&w=majority&appName=EduTech

  web:
    build:
      context: .
      dockerfile: apps/web/Dockerfile
    container_name: edutech-web
    restart: always
    ports:
      - '5173:5173'
    environment:
      VITE_API_AUTH_URL: "http://localhost:8001/api/v1"
      VITE_API_COURSE_URL: "http://localhost:8002/api/v1"
      VITE_API_QUIZ_URL: "http://localhost:8003/api/v1/quizzes"
    depends_on:
      - auth-service
      - course-service
      - quiz-service

volumes:
  postgres_data: